---
layout: page
title: "기호 수학(Symbolic Math) "
subtitle: "수능 문제지, 정답"
author:
- name: "이광춘"
  affiliation: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
tags: ["데이터 과학", "Data Science", "데이터 사이언스", "distill", "웹사이트", "과학기술", "블로그"]
date: "`r Sys.Date()`"
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: default
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: yes
editor_options: 
  chunk_output_type: console
bibliography: bibliography-cd.bib
csl: biomed-central.csl
---

```{r setup2, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

library(reticulate)
```


# 수능시험 [^ebs-exam] {#math-gre}

[^ebs-exam]: [EBS 수능시험 - 풀서비스](http://www.ebsi.co.kr/ebs/xip/xipa/retrieveSCVMainInfo.ebs?irecord=202012033)

# 성적분포 {#assume-normal}


```{r assume-normal-score}
library(tidyverse)
library(rvest)

ebs_url <- "http://www.ebsi.co.kr/ebs/xip/xipa/retrieveSCVMainInfo.ebs?irecord=202012033&targetCd=D300"

korean_tbl <- ebs_url %>% 
  read_html(encoding = 'EUC-KR') %>% 
  html_nodes(css = '#grdCutArea > section:nth-child(2) > table') %>% 
  html_table()

listviewer::jsonedit(korean_tbl)


# read_html(encoding = 'CP949') %>% 
  html_node(id = 'tbl_1')
  html_node(xpath = '//*[@id="grdCutArea"]/section[1]/table')

  html_children()
  


```





